name = "emojis"
description = "A library to replace names between colons with emojis"
version = "1.0.0"
website = "https://github.com/onox/emojis"
licenses = "Apache-2.0"
tags = ["emoji", "string", "text", "unicode"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAO-Is"]
